/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_725LnnCYm",
    "aws_user_pools_web_client_id": "3p0j9opt7iokkpi47p44afdhjg",
    "oauth": {}
};


export default awsmobile;
